version: '3.8'

services:
  backend:
    build:
      context: ./src/backend
    container_name: farmtech-backend
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app
    env_file:
      - ./src/infra/.env
    environment:
      - PYTHONPATH=/app
    networks:
      - farmtech-network

  frontend:
    build:
      context: ./src/frontend
    container_name: farmtech-frontend
    ports:
      - "8501:8501"
    volumes:
      - ./src/frontend:/app
    depends_on:
      - backend
    networks:
      - farmtech-network

  estatistica:
    build:
      context: ./src/estatistica
    container_name: farmtech-estatistica
    volumes:
      - ./src/estatistica:/estatistica
    command: ["Rscript", "/estatistica/r/estatistica.r"]
    networks:
      - farmtech-network

networks:
  farmtech-network:
    driver: bridge